# BUILD IT USING docker build -t wasaphoto-frontend:latest -f Dockerfile.frontend .
# RUN IT USING docker run -it -p 8080:80 --rm wasaphoto-frontend:latest

FROM node:lts as compiler
WORKDIR /app
COPY webui webui
WORKDIR /app/webui
RUN npm run build-prod

FROM nginx:stable
COPY --from=compiler /app/webui/dist /usr/share/nginx/html
# CMD AND EXPOSE ARE ALREADY ON NGINX CONTAINER