openapi: 3.0.3
info:
  title: WASA HW
  description: |-
    This OpenAPI document describes the WASA HW 
    OpenAPI specifications.
  version: "1"
tags:
  - name: login
  - name: username
  - name: follower
  - name: ban
  - name: user photo
  - name: user profile
  - name: user stream
  - name: likes
  - name: comments
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema: { $ref : "#/components/schemas/Username" }
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Identifier" }
              example: 
                identifier: "abcdef012345"
  /users/{userName}:
    parameters: 
      - $ref : "#/components/parameters/username"
    get:
      tags: ["user profile"]
      summary: Get the user profile
      security: 
        - BearerAuth: []
      description: |-
        Fetch all the required informations
        for a user profile page, including
        followers, following, how many photos
        have been uploaded. If user is banned
        by userName contained in path then
        the action is forbidden.
      operationId: getUserProfile
      responses:
        '200':
          description: User fetch action successful
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Profile" }
              example:
                following:
                  - user_id: "MichaelJackson"
                  - user_id: "IndianaJones"
                followers: 
                  - user_id: "Coez"
                  - user_id: "MaraFrascarelli"
                photos:
                  - photo_id: 1
                    author_id: "GabrieleLorenzini"
                    date: 2023-09-24T17:23:34Z
                  - photo_id: 2
                    author_id: "DavideFrattafalso"
                    date: 2023-09-24T17:33:34Z
        '401': { $ref : "#/components/responses/Unauthorized" }
        '403': { $ref : "#/components/responses/Forbidden" }
        '404': { $ref : "#/components/responses/NotFound" }
        '500': { $ref : "#/components/responses/InternalServerError" }
    put:
      tags: ["username"]
      summary: Sets the user name
      security: 
        - BearerAuth: []
      description: |-
        Change the actual user name to the one
        specified in the body and return a new
        identifier.
      operationId: setMyUserName
      requestBody:
        description: New user name
        content:
          application/json:
            schema: { $ref : "#/components/schemas/Username" }
            example: 
              name: Maria
        required: true
      responses:
        '200':
          description: Set user name action successful
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Identifier" }
              example: 
                identifier: "abcdef012345"
        '400': { $ref : "#/components/responses/BadRequest" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/followers/{followId}:
    parameters: 
      - $ref : "#/components/parameters/username"
      - $ref : "#/components/parameters/followId"
    put:
      tags: ["follower"]
      summary: Follow an user
      security:
        - BearerAuth: [] 
      description: |-
        The user that is userName in path
        will follow the user that is the
        followedId in path.
      operationId: followUser
      responses:
        '204': { $ref : "#/components/responses/NoContent" }
        '404': { $ref : "#/components/responses/NotFound" }
        '500': { $ref : "#/components/responses/InternalServerError" }
    delete:
      tags: ["follower"]
      summary: Unfollow an user
      security: 
        - BearerAuth: []
      description: |- 
        The user contained in the path
        will be unfollowed by the 
        active user contained in the 
        authorization header.
      operationId: unfollowUser
      responses: 
        '204': { $ref : "#/components/responses/NoContent" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/banned/{banId}:
    parameters: 
      - $ref : "#/components/parameters/username"
      - $ref : "#/components/parameters/banId"
    put:
      tags: ["ban"]
      summary: Ban an user
      security:
        - BearerAuth: [] 
      description: |-
        The user contained in the body
        will be banned only if the userID
        contained in the authorization header
        identifies the user name in the path
      operationId: banUser
      responses: 
        '204': { $ref : "#/components/responses/NoContent" }
        '403': { $ref : "#/components/responses/Forbidden" }
        '500': { $ref : "#/components/responses/InternalServerError" }
    delete:
      tags: ["ban"]
      summary: Unban an user
      security:
        - BearerAuth: [] 
      description: |-
        The user contained in the body
        will be unbanned only if the userID
        contained in the authorization header
        identifies the user name in the path
      operationId: unbanUser
      responses: 
        '204': { $ref : "#/components/responses/NoContent" }
        '403': { $ref : "#/components/responses/Forbidden" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/stream:
    parameters: 
      - $ref : "#/components/parameters/username"
    get:
      tags: ["user stream"]
      summary: Get stream of content for a user
      security: 
        - BearerAuth: []
      description: |-
        Get the stream of content
        for the user name specified
        in the path.
      operationId: getMyStream
      responses: 
        '200':
          description: Stream GET action succesful
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Photos" }
              example:
                photos:
                  - photo_id: 1
                    author_id: "Sfera99"
                    date: 2023-09-24T17:23:34Z
                  - photo_id: 2
                    author_id: "Gue98"
                    date: 2023-09-24T17:23:34Z
        '403': { $ref : "#/components/responses/Forbidden" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/photos:
    parameters: 
      - $ref : "#/components/parameters/username"
    get:
      tags: ["user photo"]
      summary: Get all photos of an user
      description: |-
        Get all the photos posted by the
        user specified in the path.
      operationId: getPhotos
      responses:
        '200':
          description: Get a list of photos
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Photos" }
              example:
                photos:
                  - photo_id: 1
                    author_id: "Sfera99"
                    date: 2023-09-24T17:23:34Z
                  - photo_id: 2
                    author_id: "Gue98"
                    date: 2023-09-24T17:23:34Z
        '403': { $ref : "#/components/responses/Forbidden" }
        '500': { $ref : "#/components/responses/InternalServerError" }
    post:
      tags: ["user photo"]
      summary: Upload a photo
      security:
        - BearerAuth: [] 
      description: |-
        Uploads a photo, date and time are calculated
        by the server when the request is made.
        Only the users by the ID specified in the header can
        upload a photo.
      operationId: uploadPhoto
      requestBody:
        description: Photo details
        content:
          multipart/form-data:
            schema: { $ref : "#/components/schemas/PhotoBin" }
        required: true
      responses:
        '201': 
          description: Photo upload action successful
          content:
            application/json:
              schema: { $ref : "#/components/schemas/Photo" }
              example:
                photo_id: 1
                author_id: Roberto4Coni
                date: 2023-09-24T17:23:34Z
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/photos/{photoId}:
    parameters: 
      - $ref : "#/components/parameters/username"
      - in: path
        name: photoId
        required: true
        schema:
          type: integer
        description: Integer ID of the user's photo
        example: 1
    delete:
      tags: ["user photo"]
      summary: Delete a photo
      security:
        - BearerAuth: [] 
      description: |- 
        Delete a photo. Only if the ID contained in
        header identifies the user that posted the photo 
        by photoID the delete is successful.
      operationId: deletePhoto
      responses:
        '204': { $ref : "#/components/responses/NoContent" }
        '400': { $ref : "#/components/responses/BadRequest" }
        '403': { $ref : "#/components/responses/Forbidden" }
        '404': { $ref : "#/components/responses/NotFound" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/photos/{photoId}/likes/{likeId}:
    parameters: 
      - $ref : "#/components/parameters/username"
      - in: path
        name: photoId
        required: true
        schema:
          type: integer
        description: Integer ID of the user's photo
        example: 1
      - in: path
        name: likeId
        required: true
        schema:
          type: integer
        description: Integer ID of the user's like
        example: 1
    delete:
      tags: ["likes"]
      summary: Unlikes a photo
      security:
        - BearerAuth: []
      description: |-
        The user identified by the header will
        unlike the photo specified by photoId in
        path of the user userName specified in
        path.
      operationId: unlikePhoto
      responses:
        '204': { $ref : "#/components/responses/NoContent" }
    put:
      tags: ["likes"]
      summary: Likes a photo
      security:
        - BearerAuth: []
      description: |-
        The user identified by the header will
        like the photo specified by photoId in
        path of the user userName specified in
        path.
      operationId: likePhoto
      responses:
        '204': { $ref : "#/components/responses/NoContent" }
        '404': { $ref : "#/components/responses/NotFound" }
        '500': { $ref : "#/components/responses/InternalServerError" }
    
  /users/{userName}/photos/{photoId}/comments:
    parameters: 
      - $ref : "#/components/parameters/username"
      - in: path
        name: photoId
        required: true
        schema:
          type: integer
        description: Integer ID of the user's photo
        example: 1
    post:
      tags: ["comments"]
      summary: Comments a photo
      security:
        - BearerAuth: []
      description: |-
        The user identified by the header will
        comment the photo specified by photoId in
        path of the user userName specified in
        path.
      operationId: commentPhoto
      responses:
        '201': { $ref : "#/components/responses/NoContent" }
        '404': { $ref : "#/components/responses/NotFound" }
        '500': { $ref : "#/components/responses/InternalServerError" }
  /users/{userName}/photos/{photoId}/comments/{commentId}:
    parameters: 
      - $ref : "#/components/parameters/username"
      - in: path
        name: photoId
        required: true
        schema:
          type: integer
        description: Integer ID of the user's photo
        example: 1
      - in: path
        name: commentId
        required: true
        schema:
          type: integer
        description: Integer ID of a comment
        example: 1
    delete:
      tags: ["comments"]
      summary: Uncomments a photo
      security:
        - BearerAuth: []
      description: |-
        If the ID contained in the header
        identifies the userName specified in
        the path and if photoId is valid and
        exists, the comment will be deleted
      operationId: uncommentPhoto
      responses:
        '204': { $ref : "#/components/responses/NoContent" }
        '500': { $ref : "#/components/responses/InternalServerError" }
      
components:
  parameters:
    username:
      in: path
      name: userName
      required: true
      schema: { $ref: '#/components/schemas/Username/properties/name' }
      description: Session ID of a user
      example: Maria
    followId: 
      in: path
      name: followId
      required: true
      schema: { $ref: '#/components/schemas/Username/properties/name' }
      description: Follow ID of an user
      example: "Mario66"
    banId:
      in: path
      name: banId
      required: true
      schema: { $ref: '#/components/schemas/Username/properties/name' }
      description: ID of an user
      example: "Yasuo99"
  responses:
    NoContent:
      description: Response with status code 204 (HTTP No Content)
    BadRequest:
      description: Response with status code 400 (HTTP Bad Request)
    Unauthorized:
      description: Response with status code 401 (HTTP Unauthorized)
    Forbidden:
      description: Response with status code 403 (HTTP Forbidden)
    NotFound:
      description: Response with status code 404 (HTTP Not Found)
    InternalServerError:
      description: Response with status code 500 (HTTP Internal Server Error)

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Identifier:
      description: |-
        A schema that describes an
        identifier for an user
      type: object
      properties:
        identifier:
          description: Unique ID of an user
          type: string
          example: "abcdef012345"
    Username:
      description: |-
        A schema that describes the
        name of the user.
      type: object
      properties:
        name:
          description: Name of an user
          type: string
          minLength: 3
          maxLength: 16
          pattern: '^.*?$'
          example: 'Maria'
    Photos:
      description: |-
        A schema that describes
        a collection of photos
      type: object
      properties:
        photos:
          description: Array of photos 
          type: array
          minItems: 0
          maxItems: 100
          items:
            $ref : '#/components/schemas/Photo'
    PhotoBin:
      description: |-
        A schema that describes a
        photo object converted in binary
      type: object
      properties:
        file:
          description: Binary file
          type: string
          format: binary
          minLength: 0
          maxLength: 100
    Photo:
      description: |-
        A object that contains all the useful
        info of a photo object
      type: object
      properties: 
        photo_id:
          description: Photo unique ID
          type: integer
          example: 484
        author_id:
          $ref : '#/components/schemas/Identifier/properties/identifier'
        date:
          description: DateTime of the uploaded photo
          type: string
          format: date-time
          example: 2023-09-24T17:23:34Z
    Profile:
      description: Profile of an user
      type: object
      properties:
        following: { $ref: "#/components/schemas/Follow" }
        followers: { $ref: "#/components/schemas/Follow" }
        photos: { $ref: "#/components/schemas/Photos/properties/photos" }
    Follow:
      description: Array of user that are followers or following
      type: array
      minItems: 0
      maxItems: 999
      items: { $ref: "#/components/schemas/User" }
    User:
      description: Info about an user such as User ID
      type: object
      properties:
        user_id: { $ref: "#/components/schemas/Username/properties/name" }
